development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_workout_planner
  pool: 5
  username: root
  password: eclips3
  host: localhost

production:
  adapter: postgresql